-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE USUÁRIO (
NOME_USUARIO VARCHAR(40),
EMAIL_USUARIO VARCHAR(40),
SENHA_USUARIO VARCHAR(40),
ID_USUARIO INTEGER PRIMARY KEY auto_increment,
ID_RESTRIÇÃO INTEGER
);

CREATE TABLE RESTRIÇÃO (
TIPO_RESTRIÇÃO VARCHAR(10),
ID_RESTRIÇÃO INTEGER PRIMARY KEY auto_increment
);

CREATE TABLE COMPRA (
DATA_COMPRA DATETIME,
VALOR_COMPRA DECIMAL(10),
ID_COMPRA INTEGER PRIMARY KEY auto_increment,
ID_USUARIO INTEGER,
FOREIGN KEY(ID_USUARIO) REFERENCES USUÁRIO (ID_USUARIO)
);

CREATE TABLE DESTINO (
CIDADE_DESTINO VARCHAR(40),
ESTADO_DESTINO VARCHAR(40),
PAÍS_DESTINO VARCHAR(40),
ID_DESTINO INTEGER PRIMARY KEY
);

CREATE TABLE PASSAGEM (
PREÇO_PASSAGEM DECIMAL(7),
DATA DATETIME,
ID_PASSAGEM INTEGER PRIMARY KEY auto_increment,
ID_DESTINO INTEGER,
FOREIGN KEY(ID_DESTINO) REFERENCES DESTINO (ID_DESTINO)
);

CREATE TABLE ITENS_COMPRA (
QTD_ITENS INTEGER,
VALOR_ITENS DECIMAL(10),
ID_PASSAGEM INTEGER,
ID_COMPRA INTEGER,
FOREIGN KEY(ID_PASSAGEM) REFERENCES PASSAGEM (ID_PASSAGEM),
FOREIGN KEY(ID_COMPRA) REFERENCES COMPRA (ID_COMPRA)
);

ALTER TABLE USUÁRIO ADD FOREIGN KEY(ID_RESTRIÇÃO) REFERENCES RESTRIÇÃO (ID_RESTRIÇÃO)
